"""Maps SeriesType slugs to their outgoing webhook event types.

Each series type is mapped to:
- a GROUP event  (``SERIES_TYPE_TO_GROUP_EVENT``)   — fires for any sample in that category
- a GRANULAR event (``SERIES_TYPE_TO_GRANULAR_EVENT``) — fires for this specific metric only

Both events are emitted for every ingestion batch.  Series types not listed here are silently skipped.
"""

from app.schemas.webhooks.event_types import WebhookEventType

# ---------------------------------------------------------------------------
# GROUP mapping  (series_type slug → group/category event)
# ---------------------------------------------------------------------------
SERIES_TYPE_TO_GROUP_EVENT: dict[str, str] = {
    # Heart & Cardiovascular
    "heart_rate": WebhookEventType.HEART_RATE_CREATED,
    "resting_heart_rate": WebhookEventType.HEART_RATE_CREATED,
    "heart_rate_recovery_one_minute": WebhookEventType.HEART_RATE_CREATED,
    "walking_heart_rate_average": WebhookEventType.HEART_RATE_CREATED,
    "atrial_fibrillation_burden": WebhookEventType.HEART_RATE_CREATED,
    "heart_rate_variability_sdnn": WebhookEventType.HEART_RATE_VARIABILITY_CREATED,
    "heart_rate_variability_rmssd": WebhookEventType.HEART_RATE_VARIABILITY_CREATED,
    "garmin_body_battery": WebhookEventType.RECOVERY_SCORE_CREATED,
    # Blood & Respiratory
    "oxygen_saturation": WebhookEventType.SPO2_CREATED,
    "peripheral_perfusion_index": WebhookEventType.SPO2_CREATED,
    "blood_glucose": WebhookEventType.BLOOD_GLUCOSE_CREATED,
    "blood_alcohol_content": WebhookEventType.BLOOD_GLUCOSE_CREATED,
    "insulin_delivery": WebhookEventType.BLOOD_GLUCOSE_CREATED,
    "blood_pressure_systolic": WebhookEventType.BLOOD_PRESSURE_CREATED,
    "blood_pressure_diastolic": WebhookEventType.BLOOD_PRESSURE_CREATED,
    "respiratory_rate": WebhookEventType.RESPIRATORY_RATE_CREATED,
    "sleeping_breathing_disturbances": WebhookEventType.RESPIRATORY_RATE_CREATED,
    "breathing_disturbance_index": WebhookEventType.RESPIRATORY_RATE_CREATED,
    "forced_vital_capacity": WebhookEventType.RESPIRATORY_RATE_CREATED,
    "forced_expiratory_volume_1": WebhookEventType.RESPIRATORY_RATE_CREATED,
    "peak_expiratory_flow_rate": WebhookEventType.RESPIRATORY_RATE_CREATED,
    # Body Composition
    "height": WebhookEventType.BODY_COMPOSITION_CREATED,
    "weight": WebhookEventType.BODY_COMPOSITION_CREATED,
    "body_fat_percentage": WebhookEventType.BODY_COMPOSITION_CREATED,
    "body_mass_index": WebhookEventType.BODY_COMPOSITION_CREATED,
    "lean_body_mass": WebhookEventType.BODY_COMPOSITION_CREATED,
    "body_fat_mass": WebhookEventType.BODY_COMPOSITION_CREATED,
    "skeletal_muscle_mass": WebhookEventType.BODY_COMPOSITION_CREATED,
    "waist_circumference": WebhookEventType.BODY_COMPOSITION_CREATED,
    # Body Temperature
    "body_temperature": WebhookEventType.BODY_TEMPERATURE_CREATED,
    "skin_temperature": WebhookEventType.BODY_TEMPERATURE_CREATED,
    "skin_temperature_deviation": WebhookEventType.BODY_TEMPERATURE_CREATED,
    "skin_temperature_trend_deviation": WebhookEventType.BODY_TEMPERATURE_CREATED,
    "garmin_skin_temperature": WebhookEventType.BODY_TEMPERATURE_CREATED,
    # Stress
    "garmin_stress_level": WebhookEventType.STRESS_CREATED,
    "electrodermal_activity": WebhookEventType.STRESS_CREATED,
    # Fitness Metrics
    "vo2_max": WebhookEventType.FITNESS_METRICS_CREATED,
    "six_minute_walk_test_distance": WebhookEventType.FITNESS_METRICS_CREATED,
    "cardiovascular_age": WebhookEventType.FITNESS_METRICS_CREATED,
    "garmin_fitness_age": WebhookEventType.FITNESS_METRICS_CREATED,
    # Activity Basic
    "steps": WebhookEventType.STEPS_CREATED,
    "energy": WebhookEventType.CALORIES_CREATED,
    "basal_energy": WebhookEventType.CALORIES_CREATED,
    "stand_time": WebhookEventType.ACTIVITY_CREATED_TIMESERIES,
    "exercise_time": WebhookEventType.ACTIVITY_CREATED_TIMESERIES,
    "physical_effort": WebhookEventType.ACTIVITY_CREATED_TIMESERIES,
    "flights_climbed": WebhookEventType.ACTIVITY_CREATED_TIMESERIES,
    "average_met": WebhookEventType.ACTIVITY_CREATED_TIMESERIES,
    "active_time": WebhookEventType.ACTIVITY_CREATED_TIMESERIES,
    "push_count": WebhookEventType.ACTIVITY_CREATED_TIMESERIES,
    "number_of_times_fallen": WebhookEventType.ACTIVITY_CREATED_TIMESERIES,
    "number_of_alcoholic_beverages": WebhookEventType.ACTIVITY_CREATED_TIMESERIES,
    "nike_fuel": WebhookEventType.ACTIVITY_CREATED_TIMESERIES,
    "hydration": WebhookEventType.ACTIVITY_CREATED_TIMESERIES,
    # Activity Distance
    "distance_walking_running": WebhookEventType.ACTIVITY_CREATED_TIMESERIES,
    "distance_cycling": WebhookEventType.ACTIVITY_CREATED_TIMESERIES,
    "distance_swimming": WebhookEventType.ACTIVITY_CREATED_TIMESERIES,
    "distance_downhill_snow_sports": WebhookEventType.ACTIVITY_CREATED_TIMESERIES,
    "distance_other": WebhookEventType.ACTIVITY_CREATED_TIMESERIES,
    # Workout / Sport Metrics
    "cadence": WebhookEventType.WORKOUT_METRICS_CREATED,
    "power": WebhookEventType.WORKOUT_METRICS_CREATED,
    "speed": WebhookEventType.WORKOUT_METRICS_CREATED,
    "workout_effort_score": WebhookEventType.WORKOUT_METRICS_CREATED,
    "estimated_workout_effort_score": WebhookEventType.WORKOUT_METRICS_CREATED,
    "walking_step_length": WebhookEventType.WORKOUT_METRICS_CREATED,
    "walking_speed": WebhookEventType.WORKOUT_METRICS_CREATED,
    "walking_double_support_percentage": WebhookEventType.WORKOUT_METRICS_CREATED,
    "walking_asymmetry_percentage": WebhookEventType.WORKOUT_METRICS_CREATED,
    "walking_steadiness": WebhookEventType.WORKOUT_METRICS_CREATED,
    "stair_descent_speed": WebhookEventType.WORKOUT_METRICS_CREATED,
    "stair_ascent_speed": WebhookEventType.WORKOUT_METRICS_CREATED,
    "running_power": WebhookEventType.WORKOUT_METRICS_CREATED,
    "running_speed": WebhookEventType.WORKOUT_METRICS_CREATED,
    "running_vertical_oscillation": WebhookEventType.WORKOUT_METRICS_CREATED,
    "running_ground_contact_time": WebhookEventType.WORKOUT_METRICS_CREATED,
    "running_stride_length": WebhookEventType.WORKOUT_METRICS_CREATED,
    "swimming_stroke_count": WebhookEventType.WORKOUT_METRICS_CREATED,
    "underwater_depth": WebhookEventType.WORKOUT_METRICS_CREATED,
    # Environmental
    "environmental_audio_exposure": WebhookEventType.ENVIRONMENTAL_CREATED,
    "headphone_audio_exposure": WebhookEventType.ENVIRONMENTAL_CREATED,
    "environmental_sound_reduction": WebhookEventType.ENVIRONMENTAL_CREATED,
    "time_in_daylight": WebhookEventType.ENVIRONMENTAL_CREATED,
    "water_temperature": WebhookEventType.ENVIRONMENTAL_CREATED,
    "uv_exposure": WebhookEventType.ENVIRONMENTAL_CREATED,
    "inhaler_usage": WebhookEventType.ENVIRONMENTAL_CREATED,
    "weather_temperature": WebhookEventType.ENVIRONMENTAL_CREATED,
    "weather_humidity": WebhookEventType.ENVIRONMENTAL_CREATED,
}

# Backwards-compat alias (was the only mapping before granular events were added)
SERIES_TYPE_TO_WEBHOOK_EVENT = SERIES_TYPE_TO_GROUP_EVENT

# ---------------------------------------------------------------------------
# GRANULAR mapping  (series_type slug → series.<slug>.created event)
# ---------------------------------------------------------------------------
SERIES_TYPE_TO_GRANULAR_EVENT: dict[str, str] = {
    "heart_rate": WebhookEventType.SERIES_HEART_RATE,
    "resting_heart_rate": WebhookEventType.SERIES_RESTING_HEART_RATE,
    "heart_rate_recovery_one_minute": WebhookEventType.SERIES_HEART_RATE_RECOVERY_ONE_MINUTE,
    "walking_heart_rate_average": WebhookEventType.SERIES_WALKING_HEART_RATE_AVERAGE,
    "atrial_fibrillation_burden": WebhookEventType.SERIES_ATRIAL_FIBRILLATION_BURDEN,
    "heart_rate_variability_sdnn": WebhookEventType.SERIES_HEART_RATE_VARIABILITY_SDNN,
    "heart_rate_variability_rmssd": WebhookEventType.SERIES_HEART_RATE_VARIABILITY_RMSSD,
    "garmin_body_battery": WebhookEventType.SERIES_GARMIN_BODY_BATTERY,
    "oxygen_saturation": WebhookEventType.SERIES_OXYGEN_SATURATION,
    "peripheral_perfusion_index": WebhookEventType.SERIES_PERIPHERAL_PERFUSION_INDEX,
    "blood_glucose": WebhookEventType.SERIES_BLOOD_GLUCOSE,
    "blood_alcohol_content": WebhookEventType.SERIES_BLOOD_ALCOHOL_CONTENT,
    "insulin_delivery": WebhookEventType.SERIES_INSULIN_DELIVERY,
    "blood_pressure_systolic": WebhookEventType.SERIES_BLOOD_PRESSURE_SYSTOLIC,
    "blood_pressure_diastolic": WebhookEventType.SERIES_BLOOD_PRESSURE_DIASTOLIC,
    "respiratory_rate": WebhookEventType.SERIES_RESPIRATORY_RATE,
    "sleeping_breathing_disturbances": WebhookEventType.SERIES_SLEEPING_BREATHING_DISTURBANCES,
    "breathing_disturbance_index": WebhookEventType.SERIES_BREATHING_DISTURBANCE_INDEX,
    "forced_vital_capacity": WebhookEventType.SERIES_FORCED_VITAL_CAPACITY,
    "forced_expiratory_volume_1": WebhookEventType.SERIES_FORCED_EXPIRATORY_VOLUME_1,
    "peak_expiratory_flow_rate": WebhookEventType.SERIES_PEAK_EXPIRATORY_FLOW_RATE,
    "height": WebhookEventType.SERIES_HEIGHT,
    "weight": WebhookEventType.SERIES_WEIGHT,
    "body_fat_percentage": WebhookEventType.SERIES_BODY_FAT_PERCENTAGE,
    "body_mass_index": WebhookEventType.SERIES_BODY_MASS_INDEX,
    "lean_body_mass": WebhookEventType.SERIES_LEAN_BODY_MASS,
    "body_fat_mass": WebhookEventType.SERIES_BODY_FAT_MASS,
    "skeletal_muscle_mass": WebhookEventType.SERIES_SKELETAL_MUSCLE_MASS,
    "waist_circumference": WebhookEventType.SERIES_WAIST_CIRCUMFERENCE,
    "body_temperature": WebhookEventType.SERIES_BODY_TEMPERATURE,
    "skin_temperature": WebhookEventType.SERIES_SKIN_TEMPERATURE,
    "skin_temperature_deviation": WebhookEventType.SERIES_SKIN_TEMPERATURE_DEVIATION,
    "skin_temperature_trend_deviation": WebhookEventType.SERIES_SKIN_TEMPERATURE_TREND_DEVIATION,
    "garmin_skin_temperature": WebhookEventType.SERIES_GARMIN_SKIN_TEMPERATURE,
    "garmin_stress_level": WebhookEventType.SERIES_GARMIN_STRESS_LEVEL,
    "electrodermal_activity": WebhookEventType.SERIES_ELECTRODERMAL_ACTIVITY,
    "vo2_max": WebhookEventType.SERIES_VO2_MAX,
    "six_minute_walk_test_distance": WebhookEventType.SERIES_SIX_MINUTE_WALK_TEST_DISTANCE,
    "cardiovascular_age": WebhookEventType.SERIES_CARDIOVASCULAR_AGE,
    "garmin_fitness_age": WebhookEventType.SERIES_GARMIN_FITNESS_AGE,
    "steps": WebhookEventType.SERIES_STEPS,
    "energy": WebhookEventType.SERIES_ENERGY,
    "basal_energy": WebhookEventType.SERIES_BASAL_ENERGY,
    "stand_time": WebhookEventType.SERIES_STAND_TIME,
    "exercise_time": WebhookEventType.SERIES_EXERCISE_TIME,
    "physical_effort": WebhookEventType.SERIES_PHYSICAL_EFFORT,
    "flights_climbed": WebhookEventType.SERIES_FLIGHTS_CLIMBED,
    "average_met": WebhookEventType.SERIES_AVERAGE_MET,
    "active_time": WebhookEventType.SERIES_ACTIVE_TIME,
    "push_count": WebhookEventType.SERIES_PUSH_COUNT,
    "number_of_times_fallen": WebhookEventType.SERIES_NUMBER_OF_TIMES_FALLEN,
    "number_of_alcoholic_beverages": WebhookEventType.SERIES_NUMBER_OF_ALCOHOLIC_BEVERAGES,
    "nike_fuel": WebhookEventType.SERIES_NIKE_FUEL,
    "hydration": WebhookEventType.SERIES_HYDRATION,
    "distance_walking_running": WebhookEventType.SERIES_DISTANCE_WALKING_RUNNING,
    "distance_cycling": WebhookEventType.SERIES_DISTANCE_CYCLING,
    "distance_swimming": WebhookEventType.SERIES_DISTANCE_SWIMMING,
    "distance_downhill_snow_sports": WebhookEventType.SERIES_DISTANCE_DOWNHILL_SNOW_SPORTS,
    "distance_other": WebhookEventType.SERIES_DISTANCE_OTHER,
    "cadence": WebhookEventType.SERIES_CADENCE,
    "power": WebhookEventType.SERIES_POWER,
    "speed": WebhookEventType.SERIES_SPEED,
    "workout_effort_score": WebhookEventType.SERIES_WORKOUT_EFFORT_SCORE,
    "estimated_workout_effort_score": WebhookEventType.SERIES_ESTIMATED_WORKOUT_EFFORT_SCORE,
    "walking_step_length": WebhookEventType.SERIES_WALKING_STEP_LENGTH,
    "walking_speed": WebhookEventType.SERIES_WALKING_SPEED,
    "walking_double_support_percentage": WebhookEventType.SERIES_WALKING_DOUBLE_SUPPORT_PERCENTAGE,
    "walking_asymmetry_percentage": WebhookEventType.SERIES_WALKING_ASYMMETRY_PERCENTAGE,
    "walking_steadiness": WebhookEventType.SERIES_WALKING_STEADINESS,
    "stair_descent_speed": WebhookEventType.SERIES_STAIR_DESCENT_SPEED,
    "stair_ascent_speed": WebhookEventType.SERIES_STAIR_ASCENT_SPEED,
    "running_power": WebhookEventType.SERIES_RUNNING_POWER,
    "running_speed": WebhookEventType.SERIES_RUNNING_SPEED,
    "running_vertical_oscillation": WebhookEventType.SERIES_RUNNING_VERTICAL_OSCILLATION,
    "running_ground_contact_time": WebhookEventType.SERIES_RUNNING_GROUND_CONTACT_TIME,
    "running_stride_length": WebhookEventType.SERIES_RUNNING_STRIDE_LENGTH,
    "swimming_stroke_count": WebhookEventType.SERIES_SWIMMING_STROKE_COUNT,
    "underwater_depth": WebhookEventType.SERIES_UNDERWATER_DEPTH,
    "environmental_audio_exposure": WebhookEventType.SERIES_ENVIRONMENTAL_AUDIO_EXPOSURE,
    "headphone_audio_exposure": WebhookEventType.SERIES_HEADPHONE_AUDIO_EXPOSURE,
    "environmental_sound_reduction": WebhookEventType.SERIES_ENVIRONMENTAL_SOUND_REDUCTION,
    "time_in_daylight": WebhookEventType.SERIES_TIME_IN_DAYLIGHT,
    "water_temperature": WebhookEventType.SERIES_WATER_TEMPERATURE,
    "uv_exposure": WebhookEventType.SERIES_UV_EXPOSURE,
    "inhaler_usage": WebhookEventType.SERIES_INHALER_USAGE,
    "weather_temperature": WebhookEventType.SERIES_WEATHER_TEMPERATURE,
    "weather_humidity": WebhookEventType.SERIES_WEATHER_HUMIDITY,
}
