-- Type of device that collected health data.
CREATE TYPE devicetype AS ENUM (
    'WATCH',
    'BAND',
    'RING',
    'PHONE',
    'SCALE',
    'OTHER',
    'UNKNOWN'
);

-- Global data lifecycle settings for archival and retention.
CREATE TABLE archival_settings (
  -- Singleton row identifier. Must always be 1.
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Days before live samples are archived. NULL means archival is disabled.
  archive_after_days INTEGER,

  -- Days before archived data is deleted. NULL means data is kept indefinitely.
  delete_after_days INTEGER,

  -- Timestamp when this archival setting was created.
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT ck_archival_settings_singleton CHECK (id = 1)
);

-- Global priority configuration for device types.
CREATE TABLE device_type_priority (
  -- Primary device type priority identifier.
  id UUID PRIMARY KEY,

  -- Device type.
  device_type devicetype NOT NULL UNIQUE,

  -- Lower number means higher priority.
  priority INTEGER NOT NULL,

  -- Timestamp when this priority row was created.
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Timestamp when this priority row was last updated.
  updated_at TIMESTAMPTZ NOT NULL
);

-- Global priority configuration for providers.
CREATE TABLE provider_priority (
  -- Primary provider priority identifier.
  id UUID PRIMARY KEY,

  -- Provider name.
  provider VARCHAR(50) NOT NULL UNIQUE,

  -- Lower number means higher priority.
  priority INTEGER NOT NULL,

  -- Timestamp when this priority row was created.
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Timestamp when this priority row was last updated.
  updated_at TIMESTAMPTZ NOT NULL
);

-- Archived aggregated time-series data.
CREATE TABLE data_point_series_archive (
  -- Primary archive row identifier.
  id UUID PRIMARY KEY,

  -- Data source this archive row belongs to.
  data_source_id UUID NOT NULL REFERENCES data_source (id) ON DELETE CASCADE,

  -- Series type definition for this archive row.
  series_type_definition_id INTEGER NOT NULL REFERENCES series_type_definition (id) ON DELETE RESTRICT,

  -- Start timestamp of the aggregation bucket.
  bucket_start_at TIMESTAMPTZ NOT NULL,

  -- Aggregation type such as avg, min, max, sum, or count.
  aggregation_type VARCHAR(32) NOT NULL,

  -- Aggregated value.
  value NUMERIC(10, 3) NOT NULL,

  -- Number of samples used for this aggregation.
  sample_count INTEGER NOT NULL,

  -- Timestamp when this archive row was created.
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT uq_archive_source_type_start_agg UNIQUE (
    data_source_id,
    series_type_definition_id,
    bucket_start_at,
    aggregation_type
  )
);

-- Lookup index for device type priority ordering.
CREATE INDEX ix_device_type_priority_priority
  ON device_type_priority (priority);

-- Lookup index for provider priority ordering.
CREATE INDEX ix_provider_priority_priority
  ON provider_priority (priority);

-- Lookup index for archive bucket start time.
CREATE INDEX ix_data_point_series_archive_bucket_start_at
  ON data_point_series_archive (bucket_start_at);