-- Add up migration script here
-- Defines the available time-series types and their canonical units.
CREATE TABLE series_type_definition (
  -- Primary series type identifier.
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Unique series type code.
  code VARCHAR(64) NOT NULL UNIQUE,

  -- Canonical unit for this series type.
  unit VARCHAR(10) NOT NULL,

  -- Timestamp when this series type was created.
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Maps a user/provider/device combination into a reusable data source identifier.
CREATE TABLE data_source (
  -- Primary data source identifier.
  id UUID PRIMARY KEY,

  -- User who owns this data source.
  user_id UUID NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,

  -- Provider name.
  provider VARCHAR(50) NOT NULL,

  -- Provider connection linked to this source. NULL for one-time imports.
  user_connection_id UUID REFERENCES user_connection (id) ON DELETE SET NULL,

  -- Device model reported by the provider.
  device_model VARCHAR(100),

  -- Device software version.
  software_version VARCHAR(50),

  -- Source name or bundle identifier. Apple HealthKit can use long bundle ids.
  source VARCHAR(100),

  -- Device type label.
  device_type VARCHAR(32),

  -- Original source name from the provider payload.
  original_source_name VARCHAR(100),

  -- Timestamp when this data source was created.
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Unified time-series data points for device metrics such as heart rate, steps, and energy.
CREATE TABLE data_point_series (
  -- Primary time-series point identifier.
  id UUID PRIMARY KEY,

  -- Provider-side external identifier.
  external_id VARCHAR(100),

  -- Data source this point belongs to.
  data_source_id UUID NOT NULL REFERENCES data_source (id) ON DELETE CASCADE,

  -- Timestamp when this point was recorded.
  recorded_at TIMESTAMPTZ NOT NULL,

  -- Timezone offset from the original data source.
  zone_offset VARCHAR(10),

  -- Numeric value for this data point.
  value NUMERIC(10, 3) NOT NULL,

  -- Series type definition for this point.
  series_type_definition_id INTEGER NOT NULL REFERENCES series_type_definition (id) ON DELETE RESTRICT,

  -- True when this point is a pre-aggregated daily total. False or NULL means granular sample.
  is_daily_total BOOLEAN,

  -- Timestamp when this point was created.
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT uq_data_point_series_source_type_time UNIQUE (
    data_source_id,
    series_type_definition_id,
    recorded_at
  )
);

-- Lookup index for data sources by user and provider.
CREATE INDEX ix_data_source_user_provider
  ON data_source (user_id, provider);

-- Unique identity for a user/provider/device/source combination.
CREATE UNIQUE INDEX uq_data_source_identity
  ON data_source (
    user_id,
    provider,
    COALESCE(device_model, ''),
    COALESCE(source, '')
  );